# Map parking data

In [1]:
# import
import pandas as pd
import json

In [2]:
# data
parking = pd.read_csv("data/Parking_Tickets.csv")

In [16]:
print parking.shape
parking.head(5)

(29824, 7)

,﻿OFFENSETYPE,LOCATION,DAY,TIME,FID,lon,lat
0,PARKING A VEHICLE IN A PARKING SPACE GOVERNED ...,LAKESHORE RD E,2016-02-16T00:00:00.000Z,2016-02-29T14:37:00.000Z,2001,43.580896,-79.554541
1,PARKING A VEHICLE IN A PARKING SPACE GOVERNED ...,LAKESHORE RD E,2016-02-16T00:00:00.000Z,2016-02-29T16:15:00.000Z,2002,43.580896,-79.554541
2,PARKING A VEHICLE IN A PARKING SPACE GOVERNED ...,50-90 BURNHAMTHORPE RD W,2016-01-30T00:00:00.000Z,2016-02-29T20:14:00.000Z,2003,43.571086,-79.660975
3,PARKING A VEHICLE IN A PARKING SPACE GOVERNED ...,56 LAKESHORE RD E,2016-02-20T00:00:00.000Z,2016-02-29T13:43:00.000Z,2004,43.552484,-79.584952
4,PARKING A VEHICLE IN A PARKING SPACE GOVERNED ...,LIVING ARTS DR,2016-01-27T00:00:00.000Z,2016-02-29T19:23:00.000Z,2005,43.586719,-79.643140

In [4]:
with open('location.json', 'r') as infile:
    location = json.load(infile)

In [5]:
parking["lon"] = 0
parking["lat"] = 0

In [15]:
for r in range(parking.shape[0]):
    if r % 100 == 0:
        print r
    add = parking.irow(r)["LOCATION"]
    if location.has_key(add) and location[add] != []:
        res = location[add]
        parking.iloc[r,5] = res[0]
        parking.iloc[r,6] = res[1]

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800

In [18]:
parking.to_csv("data_geo/Parking_Ticket.csv",index=False)